hotwired/config/routes.rb
Rails.application.routes.draw do
  resources :library_books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root "library_books#index"

  get '/simple_form' => 'library_books#simple_form'
end

hotwired/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

hotwired/app/models/library_book.rb
class LibraryBook < ApplicationRecord
  broadcasts_to ->(library_book) { 'library_books' }, target: :library_books
end

hotwired/app/models/simple_form.rb
class SimpleForm < ApplicationRecord
  
end

hotwired/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hotwired/app/controllers/library_books_controller.rb
class LibraryBooksController < ApplicationController
  before_action :set_library_book, only: %i[ show edit update destroy ]

  # GET /library_books or /library_books.json
  def index
    @library_books = LibraryBook.all
  end

  # GET /library_books/1 or /library_books/1.json
  def show
    redirect_to '/index'
  end

  # GET /library_books/new
  def new
    @library_book = LibraryBook.new
  end

  # GET /library_books/1/edit
  def edit
  end

  # POST /library_books or /library_books.json
  def create
    @library_book = LibraryBook.new(library_book_params)

    respond_to do |format|
      if @library_book.save
        format.html { redirect_to library_book_url(@library_book), notice: 'Library book was successfully created.' }
        format.json { render :show, status: :created, location: @library_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /library_books/1 or /library_books/1.json
  def update
    respond_to do |format|
      if @library_book.update(library_book_params)
        format.html { redirect_to library_book_url(@library_book), notice: "Library book was successfully updated." }
        format.json { render :show, status: :ok, location: @library_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /library_books/1 or /library_books/1.json
  def destroy
    @library_book.destroy

    respond_to do |format|
      format.html { redirect_to library_books_url, notice: "Library book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library_book
      @library_book = LibraryBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_book_params
      params.require(:library_book).permit(:title, :status, :description, :status_dat, :internal_info)
    end
end

hotwired/app/helpers/application_helper.rb
module ApplicationHelper
end

hotwired/app/helpers/library_books_helper.rb
module LibraryBooksHelper
end

hotwired/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <div class='form'>
      <%= render partial: 'simple_form' %>
      </br>
    </div>
  </body>
</html>

hotwired/app/views/library_books/_form.html.erb
<%= form_with(model: library_book) do |form| %>
  <% if library_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library_book.errors.count, "error") %> prohibited this library_book from being saved:</h2>

      <ul>
        <% library_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :status_dat, style: "display: block" %>
    <%= form.datetime_field :status_dat %>
  </div>

  <div>
    <%= form.label :internal_info, style: "display: block" %>
    <%= form.text_area :internal_info %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hotwired/app/views/library_books/_library_book.html.erb
<%= turbo_frame_tag library_book do %>
  <div class="card card-body" >
    <div class="col" style="color:red" >
      <%= library_book.title %>
    </div>
    <div class="col" >
      <%= library_book.status&.titleize %>
    </div>
    <div class="col" >
      <%= library_book&.status_dat %>
    </div>
  </div>
<% end %>

hotwired/app/views/library_books/_simple_form.html.erb
<h1>Adicione um livro novo</h1>

<%= simple_form_for LibraryBook.new do |f| %>
  <%= f.input :title %>
  <%= f.input :status %>
  <%= f.button :submit %>
<% end %>

hotwired/app/views/library_books/edit.html.erb
<h1>Editing library book</h1>

<%= render "form", library_book: @library_book %>

<br>

<div>
  <%= link_to "Show this library book", @library_book %> |
  <%= link_to "Back to library books", library_books_path %>
</div>

hotwired/app/views/library_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Library books</h1>

<div class="cores" style="text-align:center; color:red">
  <%= turbo_stream_from "library_books" %>
</div>

<%= turbo_frame_tag "library_books" do %>
  <%= render @library_books %>
<% end %>

hotwired/app/views/library_books/new.html.erb
<h1>New library book</h1>

<%= render "form", library_book: @library_book %>

<br>

<div>
  <%= link_to "Back to library books", library_books_path %>
</div>

hotwired/app/views/library_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @library_book %>

<div>
  <%= link_to "Edit this library book", edit_library_book_path(@library_book) %> |
  <%= link_to "Back to library books", library_books_path %>

  <%= button_to "Destroy this library book", @library_book, method: :delete %>
</div>